-- AlterTable
ALTER TABLE "RecetaBase" ADD COLUMN     "colorGrsL" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "esenciaGrsL" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "modoAgregados" TEXT NOT NULL DEFAULT 'simple';
